spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:file:./veloh-h2/target/db/geo
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
